#!/bin/sh
#!/usr/bin/sh

echo -en '\e]P7052505' # White (so cursor isn't visible)
echo -en '\e]P0052505' # Black
echo -en '\e]P11d551d' # Red
echo -en '\e]P28bac05' # Green
echo -en '\e]P39abb05' # Yellow

#setterm -repeat on
#set repeat rate (what's the default?)
#kdbrate -d 250

#Specify font in case no default set
setfont -h4

out/termboy ~/ROMs/pokemon_blue.gb
