#!/bin/bash

loc=~/.config/termboy/keymap.conf

if [ -e "" ]
then
  rm $loc
fi

echo "this option generates key mapping for your termboy controls"
echo "you can choose from the a-z keys and the standard 0-9 keys"
echo "any numpad mapping will result in mappings to the number row"
printf "\n"

declare -a Key_array
Key_array=("*" "*" "*" "*" "*" "*" "*" "*" "*")

echo "enter the key you want mapped to \"A\""
read temp;
Key_array[0]=$temp

echo "enter the key you want mapped to \"B\""
read temp;
Key_array[1]=$temp

echo "enter the key you want mapped to \"Start\""
read temp;
Key_array[2]=$temp

echo "enter the key you want mapped to \"Select\""
read temp;
Key_array[3]=$temp

echo "enter the key you want mapped to \"Power Switch\""
read temp;
Key_array[4]=$temp

echo "enter the key you want mapped to \"Up (D-Pad)\""
read temp;
Key_array[5]=$temp

echo "enter the key you want mapped to \"Down (D-Pad)\""
read temp;
Key_array[6]=$temp

echo "enter the key you want mapped to \"Left (D-Pad)\""
read temp;
Key_array[7]=$temp

echo "enter the key you want mapped to \"Right (D-Pad)\""
read temp;
Key_array[8]=$temp

for index in 0 1 2 3 4 5 6 7 8 
do
	Key_array[index]=$(echo ${Key_array[index]} | tr '[:upper:]' '[:lower:]')
done

for index in 0 1 2 3 4 5 6 7 8
do
	case "${Key_array[index]}" in

		1) echo "0x02" >> $loc
			;;
		2) echo "0x03" >> $loc
   			;;
		3) echo "0x04" >> $loc
			;;
		4) echo "0x05" >> $loc
			;;
		5) echo "0x06" >> $loc
			;;
		6) echo "0x07" >> $loc
			;;
		7) echo "0x08" >> $loc
			;;
		8) echo "0x09" >> $loc 
			;;
		9) echo "0x0a" >> $loc
			;;
		0) echo "0x0b" >> $loc
			;;
		q) echo "0x10" >> $loc
			;;
		w) echo "0x11" >> $loc
			;;
		e) echo "0x12" >> $loc
			;;
		r) echo "0x13" >> $loc
			;;
		t) echo "0x14" >> $loc
			;;
		y) echo "0x15" >> $loc
			;;
		u) echo "0x16" >> $loc
			;;
		i) echo "0x17" >> $loc 
			;;
		o) echo "0x18" >> $loc
			;;
		p) echo "0x19" >> $loc
			;;
		a) echo "0x1e" >> $loc
			;;
		s) echo "0x1f" >> $loc
			;;
		d) echo "0x20" >> $loc
			;;
		f) echo "0x21" >> $loc
			;;
		g) echo "0x22" >> $loc
			;;
		h) echo "0x23" >> $loc
			;;
		j) echo "0x24" >> $loc
			;;
		k) echo "0x25" >> $loc
			;;
		l) echo "0x26" >> $loc
			;;
		z) echo "0x2c" >> $loc
			;;
		x) echo "0x2d" >> $loc
			;;
		c) echo "0x2e" >> $loc
			;;
		v) echo "0x2f" >> $loc 
			;;
		b) echo "0x30" >> $loc 
			;;
		n) echo "0x31" >> $loc 
			;;
		m) echo "0x32" >> $loc 
			;;
		*) echo "invalid input"
			;;
	esac
done
